#!/bin/bash

if ! grep "## bySabi" $HOME/.bashrc >/dev/null
then
cat  >> $HOME/.bashrc <<"EOF"

## bySabi
source /etc/bash_completion.d/git-prompt
PS1=$PS1'$(__git_ps1 "\[\e[0;32m\](%s) \[\e[0m\]")'

EOF
fi
